language: java
sudo: false

cache:
  directories:
    - $HOME/.m2/

jdk:
  - oraclejdk8

script:
  - curl -O http://update.imagej.net/bootstrap.js
  - jrunscript bootstrap.js update-force-pristine
  - ./upload-site-simple.sh Hadim Hadim

branches:
  only:
    - master